main/inventory/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import  create_category, create_store_location, create_product, list_products



urlpatterns = [
    path('create-store-location/', create_store_location, name='create_store_location'),
    path('create-product/', create_product, name='create_product'),
    path('get-products/', list_products, name='get_products'),
    path('create-category/', create_category, name='create-category'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from customers.views import index
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from customers.views import template_app_time_check, template_app_date_check, appointment_cancel, waitting_list_succeed, verify, appointment_confirm, appointment_succeed, callerID, unverified, otp_resend, short_appointments, waiting_list_times
from users.views import login, privacy_policy, terms_conditions, CusLoginView
from django.conf.urls import url
from django.contrib.auth.views import LogoutView


print(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
print(settings.STATIC_ROOT)
print(staticfiles_urlpatterns())
urlpatterns = [

    path('admin/', admin.site.urls),
    path('api/', include('users.urls_api')),
    path('staff/', include('customers.urls')),
    path('account/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('', index, name='index'),
    path('verify/', verify, name='verify'),
    path('unverified/', unverified, name='unverified'),
    path('appointment-confirm/', appointment_confirm, name='appointment_confirm'),
    path('appointment-cancel/', appointment_cancel, name='appointment_cancel'),
    path('appointment-succeed/', appointment_succeed, name='appointment_succeed'),
    path('waitting-list-succeed/', waitting_list_succeed, name='waitting-list-succeed'),
    path('waiting-list-times/', waiting_list_times, name='waiting-list-times'),
    path('caller-id/', callerID, name='caller_id'),
    path('otp-resend/', otp_resend, name='otp_resend'),
    path('short-appointments/', short_appointments, name='short-appointments'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
    path('terms-conditions/', terms_conditions, name='terms-conditions'),
    path('app-date-check/', template_app_date_check, name='app-date-check'),
    path('app-time-check/', template_app_time_check, name='app-time-check'),
    # url(r'^login/$', login, name='login'),
    url(r'^login/$', CusLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    #url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sms/', include('sms.urls')),




]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# + staticfiles_urlpatterns()

main/sms/urls.py
from django.urls import path
from django.conf.urls import url
from .views import read_smss, send_ussd


urlpatterns = [
    path('read-smss/', read_smss, name='read-smss'),
    path('send-ussd/', send_ussd, name='send-ussd'),

]

main/inventory/models.py
from django.db import models
from customers.models import SalonAccount

# Create your models here.
class StoreLocation(models.Model):
    salon = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    location = models.CharField(max_length=25)
    shelf = models.CharField(max_length=4)
    box = models.CharField(max_length=4)
    class Meta:
        unique_together = ('salon', 'location', 'shelf', 'box')
    
    def __str__(self):
        return f'{self.location} {self.shelf} {self.box}'

class ProductCategory(models.Model):
    salon = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    categoryName = models.CharField(max_length=150, unique=True)

    class Meta:
        verbose_name_plural = "Product categories"
    def __str__(self):
        return f'{self.categoryName}'
class Supplier(models.Model):
    salon = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    supplierName = models.CharField(max_length=50)
    supplierTel = models.CharField(max_length=15)
    supplierEmail = models.CharField(max_length=100, null=True, blank=True)
    supplierAddress1 = models.CharField(max_length=100, null=True, blank=True)
    supplierTown = models.CharField(max_length=100, null=True, blank=True)
    supplierCounty = models.CharField(max_length=100, null=True, blank=True)
    supplierPostCode = models.CharField(max_length=10, null=True, blank=True)
    supplierCountry = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f'{self.supplierName}'
    class Meta:
        unique_together = ('salon', 'supplierName')
        unique_together = ('salon', 'supplierTel')
class Product(models.Model):
    QUALITY_CHOICES = (

        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
        )
    salon = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    productName = models.CharField(max_length=250)
    productCode = models.CharField(max_length=50)
    unit = models.CharField(max_length=50,)
    stockQuantity = models.PositiveSmallIntegerField()
    orderTime = models.DateField(null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, blank=True)
    sellPrice = models.FloatField(null=True, blank=True)
    buyPrice = models.FloatField(null=True, blank=True)
    stockInTime = models.DateField(null=True, blank=True)
    decription = models.TextField(null=True, blank=True)
    quanlity = models.PositiveSmallIntegerField(choices=QUALITY_CHOICES, blank=True, null=True)
    storeLocation = models.ForeignKey(StoreLocation, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True)
    lowStock = models.PositiveSmallIntegerField()
    
    class Meta:

        unique_together = ('salon', 'productName', 'productCode', 'supplier')
    def __str__(self):
        return f'{self.productName}'
    

    def save(self, *args, **kwargs):
        if self.sellPrice:
            self.sellPrice = round(self.sellPrice, 2)
        if self.buyPrice:
            self.buyPrice = round(self.buyPrice, 2)
        super(Product, self).save(*args, **kwargs)

main/inventory/forms.py
from django import forms

class CategoryCreateForm(forms.Form):
    product_name = forms.CharField(label='Product name', max_length=100)
    product_code = forms.CharField(label='Product code', max_length=50, required=False)
    stock_quantity = forms.IntegerField(label='Stock quantity', )

main/inventory/views.py
from django.shortcuts import render
from .models import Product, StoreLocation, Supplier, ProductCategory
from django.contrib import messages
from customers.models import SalonAccount
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotFound

# Create your views here.


def create_store_location(request):
    salon = request.user.salonAcc
    storeLocations = StoreLocation.objects.filter(salon=salon)
    _popup = request.GET.get('_popup')
    print(_popup)
    context = {
        'storeLocations':storeLocations,
        'popup':_popup
    }
    if request.method == 'POST':
        reqst = request.POST
        try:
            StoreLocation(salon=salon, location=reqst['location'], shelf=reqst['shelf'], box=reqst['box']).save()
            messages.info(request, 'Store Location {} {} {} created'.format(reqst['location'], reqst['shelf'], reqst['box']))
            return render(request, 'inventory/create_store_location.html', context)
        except:
            messages.error(request, 'Store Location {} {} {} already exit'.format(reqst['location'], reqst['shelf'], reqst['box']))
            return render(request, 'inventory/create_store_location.html', context)
    else:

        return render(request, 'inventory/create_store_location.html', context)
from .forms import CategoryCreateForm
def create_category(request):
    form = CategoryCreateForm()
    return render (request, 'inventory/create_category.html', {'form':form} )
def create_product(request):
    salon = request.user.salonAcc
    storeLocations = StoreLocation.objects.filter(salon=salon)
    products = Product.objects.filter(salon=salon).order_by('-stockInTime')[:20]
    context = {
        'products':products,
        'storeLocations':storeLocations
    }
    if request.method == 'POST':
        reqst = request.POST
        try:
            product = Product(salon=salon,
                    productName=reqst['productName'],
                    productCode=reqst['productCode'],
                    unit=reqst['unit'],
                    stockQuantity=reqst['stockQuantity'],
                    lowStock=reqst['lowStock'],
                
                    decription=reqst['decription'],
                    
                    storeLocation=StoreLocation.objects.filter(pk=reqst['storeLocation']).first(),
                    
                    )
            if reqst['supplier']:
                product.supplier=Supplier.objects.filter(pk=reqst['supplier']).first(),
            if reqst['category']:
                product.category=ProductCategory.objects.filter(pk=reqst['category']).first(),
            if reqst['orderTime']:
                product.orderTime=datetime.strptime(reqst['orderTime'], '%Y-%m-%d')
            if reqst['stockInTime']:
                product.stockInTime=datetime.strptime(reqst['stockInTime'], '%Y-%m-%d')
            if reqst['sellPrice']:
                product.sellPrice=float(reqst['sellPrice'])
            if reqst['buyPrice']:
                product.buyPrice=float(reqst['buyPrice'])
            if reqst['quanlity']:
                product.quanlity=reqst['quanlity']

            product.save()
            messages.info(request, 'Product {} {} created'.format(reqst['productName'], reqst['productCode']))
            return render(request, 'inventory/create_product.html', context)
        except:
            # messages.error(request, 'Product {} {} already exit'.format(reqst['productName'], reqst['productCode']))
            return render(request, 'inventory/create_product.html', context)
    else:

        return render(request, 'inventory/create_product.html', context)

def list_products(request):
    salon = request.user.salonAcc
    products = Product.objects.filter(salon=salon)
    context = {
        "products":products
    }
    return JsonResponse(context)

main/inventory/templates/inventory/admin_base.html
<head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

    

<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

main/inventory/templates/inventory/create_category.html
{% extends 'inventory/admin_base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form class="form-horizontal" method="post">{% csrf_token %}
    <fieldset>
        <legend>{{ title }}</legend>
        {% for field in form %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
{% endblock content%}

main/inventory/templates/inventory/create_product.html
{% extends "customers/base.html" %} {% load static %} {% block content%}
<div class="row justify-content-center mt-5 p-2">
  <div class="col-sm-12 col-md-9 col-lg-6 container">
    <form method="POST">
      {%csrf_token %}
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Add Product</h5>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <div>
              <label class="required" for="id_productName">ProductName:</label>

              <input
                type="text"
                name="productName"
                class="form-control"
                maxlength="250"
                required=""
                id="id_productName"
              />
            </div>
          </div>

          <div class="mb-3">
            <div>
              <label class="required" for="id_productCode">ProductCode:</label>

              <input
                type="text"
                name="productCode"
                class="form-control"
                maxlength="50"
                required=""
                id="id_productCode"
              />
            </div>
          </div>
          <div class="mb-3">
            <div class="card">
              <div class="container">
                <div class="row">
                  <div class="col-md-6 mb-2">
                    <label for="id_supplier">Supplier Name</label>

                    <input
                      type="text"
                      name="supplier_name"
                      class="form-control"
                      maxlength="250"
                      id="id_supplier_name"
                      class="form-control"
                      required=""
                    />
                  </div>
                  <div class="col-md-6">
                    <label for="id_supplier">Supplier Tel</label>

                    <input
                      type="text"
                      name="supplier_tel"
                      class="form-control"
                      maxlength="250"
                      id="id_supplier_tel"
                      class="form-control"
                      required=""
                    />
                  </div>
                </div>
                <div>
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Supplier</th>
                        <th scope="col">Tel</th>

                      </tr>
                    </thead>
                    <tbody id="supplier_table">

                    </tbody>
                  </table>
                  <div class="row">
                  <div class="col-md-6">

                  </div>
                  <div class="col-md-6">
                                <a
                class="btn"
                id="change_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/change/?_to_field=id&amp;_popup=1"
                title="Change selected store location"
                ><img
                  src="/static/admin/img/icon-changelink.svg"
                  alt="Change" /></a
              ><a
                class="btn"
                target="popup"
                id="add_id_storeLocation"
                href="/inventory/add-store-location/"
                onclick="window.open('{% url 'create_product' %}?_popup=1','popup','width=600,height=600'); return false;"
                title="Add another store location"
                ><img src="/static/admin/img/icon-addlink.svg" alt="Add" /></a
              ><a
                class="btn"
                id="delete_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/delete/?_to_field=id&amp;_popup=1"
                title="Delete selected store location"
                ><img src="/static/admin/img/icon-deletelink.svg" alt="Delete"
              /></a>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label class="required" for="id_stockQuantity"
                >StockQuantity:</label
              >

              <input
                type="number"
                name="stockQuantity"
                class="form-control"
                min="0"
                required=""
                id="id_stockQuantity"
              />
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label class="required" for="id_lowStock">Low Stock:</label>

              <input
                type="number"
                name="lowStock"
                class="form-control"
                min="0"
                required=""
                id="id_stockQuantity"
              />
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label class="required" for="id_unit">Unit:</label>

              <input
                type="text"
                name="unit"
                class="form-control"
                maxlength="50"
                id="id_unit"
                required=""
              />
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label for="id_storeLocation">StoreLocation:</label>
              <a
                class="btn"
                id="change_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/change/?_to_field=id&amp;_popup=1"
                title="Change selected store location"
                ><img
                  src="/static/admin/img/icon-changelink.svg"
                  alt="Change" /></a
              ><a
                class="btn"
                id="add_id_storeLocation"
                href="/admin/inventory/storelocation/add/?_to_field=id&amp;_popup=1"
                onclick="window.open('{% url 'create_store_location' %}?_popup=1','popup','width=600,height=600'); return false;"
                title="Add another store location"
                ><img src="/static/admin/img/icon-addlink.svg" alt="Add" /></a
              ><a
                class="btn"
                id="delete_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/delete/?_to_field=id&amp;_popup=1"
                title="Delete selected store location"
                ><img src="/static/admin/img/icon-deletelink.svg" alt="Delete"
              /></a>

              <select
                class="form-control"
                name="storeLocation"
                id="id_storeLocation"
                required=""
              >
                <option value="" selected="">---------</option>
                {% for location in storeLocations %}
                <option value="{{location.pk}}">{{location}}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <div class="mb-3">
            <div>
              <label for="id_stockInTime">Stocked in Time:</label>
              <input
                type="date"
                name="stockInTime"
                class="form-control"
                size="10"
                id="id_stockInTime"
              />
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label for="id_quanlity">Quanlity:</label>

              <select class="form-control" name="quanlity" id="id_quanlity">
                <option value="" selected="">---------</option>

                <option value="1">1</option>

                <option value="2">2</option>

                <option value="3">3</option>

                <option value="4">4</option>

                <option value="5">5</option>
              </select>
            </div>
          </div>

          <div class="mb-3">
            <div>
              <label for="id_category">Category:</label>
              <a
                class="btn"
                id="change_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/change/?_to_field=id&amp;_popup=1"
                title="Change selected store location"
                ><img
                  src="/static/admin/img/icon-changelink.svg"
                  alt="Change" /></a
              ><a
                class="btn"
                target="popup"
                id="add_id_storeLocation"
                href="/inventory/add-store-location/"
                onclick="window.open('{% url 'create_product' %}?_popup=1','popup','width=600,height=600'); return false;"
                title="Add another store location"
                ><img src="/static/admin/img/icon-addlink.svg" alt="Add" /></a
              ><a
                class="btn"
                id="delete_id_storeLocation"
                data-href-template="/admin/inventory/storelocation/__fk__/delete/?_to_field=id&amp;_popup=1"
                title="Delete selected store location"
                ><img src="/static/admin/img/icon-deletelink.svg" alt="Delete"
              /></a>
              <select class="form-control" name="category" id="id_category">
                <option value="" selected="">---------</option>
              </select>
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label for="id_orderTime">OrderTime:</label>

              <input
                type="date"
                name="orderTime"
                class="form-control"
                min="0"
                id="id_orderTime"
              />
            </div>
          </div>

          <div class="mb-3">
            <div>
              <label for="id_sellPrice">SellPrice:</label>

              <input
                type="number"
                name="sellPrice"
                step="any"
                id="id_sellPrice"
                class="form-control"
              />
            </div>
          </div>

          <div class="mb-3">
            <div>
              <label for="id_buyPrice">BuyPrice:</label>

              <input
                type="number"
                name="buyPrice"
                step="any"
                id="id_buyPrice"
                class="form-control"
              />
            </div>
          </div>
          <div class="mb-3">
            <div>
              <label for="id_decription">Decription:</label>

              <textarea
                name="decription"
                cols="40"
                rows="10"
                class="form-control"
                id="id_decription"
              ></textarea>
            </div>
          </div>

          <div class="row" style="margin: 0px">
            <button
              type="submit"
              value="Save"
              class="btn btn-block btn-primary mt-1"
              name="_save"
            >
              Save
            </button>

            {% comment %}
            <button
              type="submit"
              value="Save and add another"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_addanother"
            >
              Save and add another
            </button>
            <button
              type="submit"
              value="Save and continue editing"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_continue"
            >
              Save and continue editing
            </button>
            {% endcomment %}
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-4 container">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Product</h6>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Product Name</th>
            <th scope="col">Product Code</th>
            <th scope="col">Stock-in Time</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
          <tr id="products">
            {% comment %}
            <td>{{product.productName}}</td>
            <td>{{product.productCode}}</td>
            <td>{{product.stockInTime}}</td>
            {% endcomment %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content%}

main/inventory/templates/inventory/create_product_category.html
{% extends "customers/base.html" %} {% load static %} {% block content%}
{% if not popup %}
<div class="row justify-content-center mt-5 p-2">
{% else %}
<div class="row p-2">
{% endif %}
  <div class="col-sm-12 col-md-9 col-lg-6 container">
    <form method="POST">
      {%csrf_token %}
      <div class="card mb-2">
        <div class="card-header">
          <h5 class="card-title">Create Product Category</h5>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <label for="categoryName" class="form-label"
              >Category Name</label
            >
            <input
              type="text"
              class="form-control"
              id="categoryName"
              placeholder=""
              name="categoryName"
              required
            />
          </div>
         

          <div class="row" style="margin: 0px">
            <button
              type="submit"
              value="Save"
              class="btn btn-block btn-primary mt-1"
              name="_save"
            >
              Save
            </button>

            {% comment %}
            <button
              type="submit"
              value="Save and add another"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_addanother"
            >
              Save and add another
            </button>
            <button
              type="submit"
              value="Save and continue editing"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_continue"
            >
              Save and continue editing
            </button>
            {% endcomment %}
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="col-sm-12 col-md-3 col-lg-3 container">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Product Categories</h6>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Categories</th>

          </tr>
        </thead>
        <tbody>
          {% for cat in categories %}
          <tr>
            <td>{{cat.categoryName}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content%}

main/inventory/templates/inventory/create_store_location.html
{% extends "customers/base.html" %} {% load static %} {% block content%}
{% if not popup %}
<div class="row justify-content-center mt-5 p-2">
{% else %}
<div class="row p-2">
{% endif %}
  <div class="col-sm-12 col-md-9 col-lg-6 container">
    <form method="POST">
      {%csrf_token %}
      <div class="card mb-2">
        <div class="card-header">
          <h5 class="card-title">Add store location</h5>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <label for="location" class="form-label"
              >Location</label
            >
            <input
              type="text"
              class="form-control"
              id="location"
              placeholder=""
              name="location"
              required
            />
          </div>
          <div class="mb-3">
            <label for="shelf" class="form-label"
              >Shelf</label
            >
            <input
              type="text"
              class="form-control"
              id="shelf"
              placeholder=""
              name="shelf"
              required
            />
          </div>
          <div class="mb-3">
            <label for="box" class="form-label">Box</label>
            <input
              type="text"
              class="form-control"
              id="box"
              placeholder=""
              name="box"
              required
            />
          </div>

          <div class="row" style="margin: 0px">
            <button
              type="submit"
              value="Save"
              class="btn btn-block btn-primary mt-1"
              name="_save"
            >
              Save
            </button>

            {% comment %}
            <button
              type="submit"
              value="Save and add another"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_addanother"
            >
              Save and add another
            </button>
            <button
              type="submit"
              value="Save and continue editing"
              class="btn btn-block btn-primary mt-1 disabled"
              name="_continue"
            >
              Save and continue editing
            </button>
            {% endcomment %}
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="col-sm-12 col-md-3 col-lg-3 container">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Store Location</h6>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Location</th>
            <th scope="col">Shelf</th>
            <th scope="col">Box</th>
          </tr>
        </thead>
        <tbody>
          {% for location in storeLocations %}
          <tr>
            <td>{{location.location}}</td>
            <td>{{location.shelf}}</td>
            <td>{{location.box}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content%}