main/customers/urls.py
from django.urls import path
from django.conf.urls import url
from .views import customer_appointment_cancel, logoff_customer, not_customer, get_customer_api, delete_smss, appointments_json, read_smss , push_callerID, test_login, template_app_time_check, template_app_date_check ,customer_search ,get_customer, callerID, add_locker, services, boxes, appointments, customers, customer_create, appointment_create, appoinment_update, customer_delete ,customer_update, box_check, clean_boxs, appointments_view


urlpatterns = [
    path('boxes/', boxes, name='boxes'),
    path('boxes/add', add_locker, name='add-boxes'),
    path('boxes/clean', clean_boxs, name='clean-boxes'),
    path('boxes/check/<int:pk>/', box_check, name='check-box'),
    path('customers/', customers, name='customers'),
    path('', appointments, name='appointments'),
    path('customers/create/', customer_create, name='create-customer'),
    path('customers/update/<int:pk>/', customer_update, name='update-customer'),
    path('customers/delete/<int:pk>/', customer_delete, name='delete-customer'),
    path('appointment/create/', appointment_create, name='create-appointment'),
    path('appointment/update/<int:pk>/', appoinment_update, name='update-appointment'),
    path('appointments/view/', appointments_view, name='view-appointments'),
    path('appointments/json/', appointments_json, name='appointments-json'),
    path('services/', services, name='services'),
    path('callerid/', callerID, name='callerid'),
    path('push_callerid/', push_callerID, name='push-callerid'),
    path('get-customer/', get_customer, name='get-customer'),
    path('get-customer-api/', get_customer_api, name='get-customer-api'),
    path('customer_search/', customer_search, name='customer-search'),
    path('read_smss/', read_smss, name='read-smss'),
    path('delete-smss/', delete_smss, name='delete-smss'),
    path('not-customer/', not_customer, name='not-customer'),
    path('logoff-customer/', logoff_customer, name='logoff-customer'),
    path('appointment/cancel/<int:pk>/', customer_appointment_cancel, name='customer-cancel-appointment'),

    


    # path('test-login/', test_login, name='test-login'),


    



]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from customers.views import index
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from customers.views import template_app_time_check, template_app_date_check, appointment_cancel, waitting_list_succeed, verify, appointment_confirm, appointment_succeed, callerID, unverified, otp_resend, short_appointments, waiting_list_times
from users.views import login, privacy_policy, terms_conditions, CusLoginView
from django.conf.urls import url
from django.contrib.auth.views import LogoutView


print(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
print(settings.STATIC_ROOT)
print(staticfiles_urlpatterns())
urlpatterns = [

    path('admin/', admin.site.urls),
    path('api/', include('users.urls_api')),
    path('staff/', include('customers.urls')),
    path('account/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('', index, name='index'),
    path('verify/', verify, name='verify'),
    path('unverified/', unverified, name='unverified'),
    path('appointment-confirm/', appointment_confirm, name='appointment_confirm'),
    path('appointment-cancel/', appointment_cancel, name='appointment_cancel'),
    path('appointment-succeed/', appointment_succeed, name='appointment_succeed'),
    path('waitting-list-succeed/', waitting_list_succeed, name='waitting-list-succeed'),
    path('waiting-list-times/', waiting_list_times, name='waiting-list-times'),
    path('caller-id/', callerID, name='caller_id'),
    path('otp-resend/', otp_resend, name='otp_resend'),
    path('short-appointments/', short_appointments, name='short-appointments'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
    path('terms-conditions/', terms_conditions, name='terms-conditions'),
    path('app-date-check/', template_app_date_check, name='app-date-check'),
    path('app-time-check/', template_app_time_check, name='app-time-check'),
    # url(r'^login/$', login, name='login'),
    url(r'^login/$', CusLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    #url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sms/', include('sms.urls')),




]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# + staticfiles_urlpatterns()

main/sms/urls.py
from django.urls import path
from django.conf.urls import url
from .views import read_smss, send_ussd


urlpatterns = [
    path('read-smss/', read_smss, name='read-smss'),
    path('send-ussd/', send_ussd, name='send-ussd'),

]

main/customers/models.py
from django.db import models
from users.models import SalonAccount
from pathlib import Path
import logging, os
from django.core.cache import cache
from datetime import timedelta, datetime
from django.utils import timezone
from logs.models import ExcetionLogs
import traceback
from django.conf import settings

logs_path = os.path.join(Path(settings.BASE_DIR).parents[0], 'logs')

logger = logging.getLogger(__name__)
logger.setLevel(logging.WARNING)

formatter = logging.Formatter('%(asctime)s:%(name)s:%(message)s')

file_handler = logging.FileHandler(os.path.join(logs_path, 'customers.log'))

file_handler.setLevel(logging.WARNING)
file_handler.setFormatter(formatter)

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(formatter)

logger.addHandler(file_handler)
logger.addHandler(stream_handler)


# Create your models here.

class SalonStylist(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, blank=True)
    mobile = models.CharField(max_length=15, blank=True)
    def __str__(self):
        return "{} {}".format(self.firstName, self.lastName)

class SalonEquipment(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    def __str__(self):
        return "{}".format(self.name)



class PedicureChairs(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return "{}".format(self.name)



class Customer(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    mobile = models.CharField(max_length=15, null=True, blank=True)
    tel = models.CharField(max_length=15, null=True, blank=True)
    address_1 = models.CharField(max_length=50, null=True, blank=True)
    address_2 = models.CharField(max_length=50, null=True, blank=True)
    town = models.CharField(max_length=50, null=True, blank=True)
    postCode = models.CharField(max_length=10, null=True, blank=True)
    notice = models.TextField(null=True, blank=True)

    class Meta:
        unique_together = ('salonAcc', 'mobile', 'firstName', 'lastName')

    def __str__(self):
        return "{} {}".format(self.firstName, self.lastName ,self.mobile) 

class CustomerSession(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    session = models.CharField(max_length=32)
    expired = models.DateTimeField()


class CustomerNotice(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    notice = models.CharField(max_length=250)
    def __str__(self):
        return f'{self.customer} {self.notice}'
    
class CustomerVerify(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    verify_id = models.CharField(max_length=15, unique=True)
    verify_code = models.CharField(max_length=6)
    created = models.DateTimeField(auto_created=True)
    def __str__(self):
        return "{} {}".format(self.customer, self.verify_id ,self.verify_code) 



class CustomerBox(models.Model):

    boxNumber = models.PositiveSmallIntegerField()
    customer = models.OneToOneField(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    lastUsed = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return f'{self.boxNumber} {self.lastUsed}'

class StoreLocker(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    boxNumber = models.PositiveSmallIntegerField()
    customer = models.OneToOneField(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    lastUsed = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('salonAcc', 'boxNumber')
    def __str__(self):
        return "{}".format(self.boxNumber)

class Service(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    serviceName = models.CharField(max_length=50)
    
    def __str__(self):
        return "{}".format(self.serviceName)

class ServiceBlock(models.Model):
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, blank=True, null=True)
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    length = models.PositiveSmallIntegerField()
    pedicure_chair_length = models.PositiveSmallIntegerField(null=True, blank=True)
    # pedChair = models.ForeignKey(PedicureChairs, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.name)



class ExtraServiceBlock(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    length = models.SmallIntegerField()
    frontEnd = models.BooleanField(default=True)
    def __str__(self):
        return "Extra service {} {}".format(self.name, self.length)     

class StylistServiceLength(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    stylist = models.ForeignKey(SalonStylist, on_delete=models.CASCADE)
    service = models.ForeignKey(ServiceBlock, on_delete=models.CASCADE)
    length = models.PositiveSmallIntegerField()

class StylistExtraServiceLength(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    stylist = models.ForeignKey(SalonStylist, on_delete=models.CASCADE)
    extrsService = models.ForeignKey(ExtraServiceBlock, on_delete=models.CASCADE)
    length = models.PositiveSmallIntegerField()

class AppointmentStatus(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    status = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return str(self.status)


class Appointment(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    dateTime = models.DateTimeField(null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    status = models.ForeignKey(AppointmentStatus, on_delete=models.SET_NULL, null=True, blank=True)
    # status = models.ForeignKey(AppointmentStatus, on_delete=models.SET_NULL, null=True, blank=True)
    stylist = models.ForeignKey(SalonStylist, on_delete=models.CASCADE)
    special = models.BooleanField(default=False)
    notice = models.TextField(blank=True)
    service = models.ForeignKey(ServiceBlock, on_delete=models.CASCADE)

    extras = models.ManyToManyField(ExtraServiceBlock, blank=True)
    chair = models.ForeignKey(PedicureChairs, on_delete=models.SET_NULL, null=True, blank=True)
    cancelID = models.CharField(max_length=50, unique=True)
    STATUS_CHOICES = (
    (0, 'Pendding'),
    (1, 'Processing'),
    (2, 'Done'),
    (3, 'Cancelled'),
    (4, 'Not Turned Up'),
    )
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        unique_together = ['customer', 'dateTime', 'service', 'salonAcc', 'stylist']

    def __str__(self):
        return '{}'.format(str(self.salonAcc))


class ClosedDay(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    date = models.DateField()
    def __str__(self):
        return '{}'.format(str(self.date))

class WeeklyCloseDay(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    DAY_CHOICES = (
    (0, 'Moday'),
    (1, 'Tuesday'),
    (2, 'Wednesday'),
    (3, 'Thursday'),
    (4, 'Friday'),
    (5, 'Saturday'),
    (6, 'Sunday'),
    )
    day = models.PositiveSmallIntegerField(choices=DAY_CHOICES)
    def __str__(self):
        DAY_CHOICES = (
            (0, 'Moday'),
            (1, 'Tuesday'),
            (2, 'Wednesday'),
            (3, 'Thursday'),
            (4, 'Friday'),
            (5, 'Saturday'),
            (6, 'Sunday'),
            )
        for day in DAY_CHOICES:
            if self.day in day:
                closedDay = day[1]
        return str(closedDay)   

class SpecialOpenTime(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    date = models.DateField()
    openTime = models.TimeField()
    closeTime = models.TimeField()

    

    class Meta:
        verbose_name = "Special OpenTime"
        verbose_name_plural = "Special OpenTimes"

    def __str__(self):
        return str(self.date)

class GenaralOpenTime(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    openTime = models.TimeField()
    closeTime = models.TimeField()

    def __str__(self):
        return "Open {} Colsed {}".format(str(self.openTime), str(self.closeTime))

class OpenTimes(models.Model):
    DAY_CHOICES = (
    (0, 'Moday'),
    (1, 'Tuesday'),
    (2, 'Wednesday'),
    (3, 'Thursday'),
    (4, 'Friday'),
    (5, 'Saturday'),
    (6, 'Sunday'),
    )
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    openTime = models.TimeField(null=True, blank=True)
    closeTime = models.TimeField(null=True, blank=True)
    day = models.PositiveSmallIntegerField(choices=DAY_CHOICES)
    def __str__(self):
        return "Day {} Open {} Colsed {}".format(str(self.day), str(self.openTime), str(self.closeTime))

class QueueSMS(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE, null=True)
    message = models.CharField(max_length=159)
    destination = models.CharField(max_length=13)
    createTime = models.DateTimeField(auto_now=True)

    
class TemplateAppointment(models.Model):
    salonAcc = models.ForeignKey(SalonAccount, on_delete=models.CASCADE)
    appoinmentID = models.CharField(max_length=25)

main/customers/templates/customers/appointment_create_form.html
{% extends "customers/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}




  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="card card-body">
          <div class="row">
            <div class="col">
            <h3>Appointment</h3>
            </div>
            <div class="col">
              <h6>Prefer Time: {{prefer_time|date:'l'}} {{prefer_time|date:'d-m-Y H:i:s'}}</h6>
    
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="card card-body">
          <div class="form-group">
          <!-- Form start -->



              <div class="row">                                    
                <div class="col form-group">
                    <h5>Customer</h5>
                </div>

                  <div class="col form-group">

                        <input id="id_box" name="box" type="text" placeholder="Box number" class="form-control input-md">
                  </div>
              </div>
              <form method="POST">
                {% csrf_token %}
              <input type="hidden" name="salon_account" id="salon_account" value="{% url 'salonaccount-detail' salonAcc.pk %}"> 
              {% comment %} <input type="hidden" name="viewdate" value="{{appntDate}}"> {% endcomment %}
              <input type="hidden" id="prefer_time" name="prefer_time" value="{{prefer_time|date:'Y-m-d H:i:s'}}"> 
              {% comment %} <input type="hidden" name="stylist" value="{{appntStylist.pk}}"> {% endcomment %}
              <input type="hidden" id="current_appointment" name="current_appointment" value="">  
              <!-- Text input-->                      
              <div id="cus_info" class="row">
                
                  <div class="col-xl-2">
                    <div class="form-group">
                        <label class="control-label" for="cus_id">ID</label>
                        <input id="cus_id" name="cus_id" type="text" class="form-control input-md">
                    </div>
                </div>
                <div class="col-xl-3">
                    <div class="form-group">
                        <label class="control-label" for="id_firstName">Firstname</label>
                        <input id="id_firstName" name="firstName" type="text" placeholder="Firstname" class="form-control input-md" required="">
                    </div>
                </div>
                <div class="col-xl-3">
                    <div class="form-group">
                        <label class="control-label" for="id_lastName">Lastname</label>
                        <input id="id_lastName" name="lastName" type="text" placeholder="Lastname" class="form-control input-md" required="">
                    </div>
                </div>
                
                <div class="col-xl-3">
                    <div class="form-group">
                        <label class="control-label" for="id_mobile">Mobile</label>
                        <input id="id_mobile" name="mobile" type="tel" placeholder="Mobile" class="form-control input-md">
                    </div>
                </div>
            
                <div class="col-xl-1" style="margin-top:40px; padding-left: auto;">
                  <div class="form-group">
                      <button class="btn btn-sm btn-danger" type="button" id="update_customer" name="update_customer" class="btn btn-dark">Update</button>
                  </div>
                </div>
              </div>
              <table id="myTable" style="margin:0px; height:150px; width:100%; overflow:auto;">             
                {% comment %} <thead class="thead-dark">
                  <tr>
                    <th width="10%">ID</th>
                    <th width="15%">FirstName</th>
                    <th width="15%">LastName</th>
                    <th width="15%">Mobile</th>
                    <th width="20%">Not Turned Up</th>
                    <th width="20%">Notice</th>
                    <th width="5%">Box</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- {% for customer in customers %}
                  <tr>
                    <td id="firstName">{{customer.firstName}}</td>
                    <td id="lastName">{{customer.lastName}}</td>
                    <td id="mobile">{{customer.mobile}}</td>
                    <td id="box">{{customer.box}}</td>
                  </tr>
                  {% endfor %} -->
                </tbody> {% endcomment %}
              </table>
     
         
 
              <!-- Select Basic -->
            <div id="appointment">
              
 
              <div class="row">
                <div class="col-md-6" style="margin-top:0px">
                  <div class="form-group">
                    <label class="control-label" for="service"><h5>Appointment For</h5></label>
                    <select id="service" name="service" class="form-control">
                      {% for service in serviceblocks %}
                        <option  value={{service.pk}}>{{service.name}}</option>
                      {% endfor %}                                                                        
                    </select>
                  </div>
                </div>
                <div class="col-md-6" style="margin-top:0px">
                  <div class="form-group">
                    <label class="control-label" for="stylist"><h5>Stylist</h5></label>
                      <select id="stylist" name="stylist" class="form-control">
                        <option value="">Not prefered</option>
                        {% for stylist in stylists %}                                
                         <option value="{{stylist.pk}}">{{stylist}}</option>
                        {% endfor %}                                                                  
                      </select>
                  </div>
                </div>
              </div>

 

              <!-- Check boxes -->         
              <div class="form-group">
                  <label class="control-label" for="appointmentfor">Extra services</label>
                  <div class="card card-body">
                    <div class="row ">
                    {% for extra in extraservices %}
                      <div class="col-md-4">
                        <label for="{{extra}}"> {{extra.name}}</label>
                        <input type="checkbox" id="{{extra.name}}" name="{{extra.name}}" value="">
                      </div>
                    {% endfor %}
                    </div>                                 
                  </div>                                                                 
              </div>
            </div>
              <!-- Text input-->  
              <div class="form-group">
                  <label class="control-label" for="notice">Notice</label>
                  <input id="notice" name="notice" type="text" placeholder="Notice to Creatip team!" class="form-control input-md">
              </div>         

                <div class="row" id="datetime">                                                                                                                                             
                  <div class="col-md-6" style="margin-top:0px">
                    <label class="control-label" for="date">Available Date</label>
                      <select class="form-control" name="date" id="date">
   
                      </select>
                  </div>  


                  <div class="col-md-6" style="margin-top:0px">
                      <label class="control-label" for="time">Available Time</label>
                          <select class="form-control" name="time" id="time">
     
                          </select>
                  </div>                                                                                                                                                                                         
                </div>
                          {% comment %} {% if messages %}
            {% for message in messages %}
              <div class="alert alert-warning">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %} {% endcomment %}
                <!-- Button -->  
                  <div class="col-md-12" style="margin-top:25px">
                    <div class="form-group">
                        <button id="appontbutton" name="appontbutton" class="btn btn-dark">Make An Appointment</button>
                    </div>
                  </div>
                

            </form>
            <!-- form end -->                                          
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% comment %} <style>
    /* scrolltable rules */
  table  { margin-top:  20px; display: inline-block; overflow: auto; }
  th div { margin-top: -20px; position: absolute; }

  /* design */
  table { border-collapse: collapse; }
  tr:nth-child(even) { background: #EEE; }
</style> {% endcomment %}





{% endblock content %}

  {% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static '/js/appointment_create.js'%}"></script>
<script>
$(document).on("click", "#cus_info", function(){
  // console.log(this.children)
  let elements = this.children
  $.each(elements, function(index, item) {
    if (this.name == 'cus_firstname'){
      console.log(this)
    }
    
    
  })
});
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static '/js/customer.js'%}"></script>


    {% endblock js %}

main/customers/templates/customers/availDates_ajax.html
<select class="form-control" name="date" id="date">
    {% for appdate in availDates %}
        {% if appdate == prefer_date %}
            <option selected value="{{appdate|date:'Y-m-d'}}">{{appdate|date:"l"}} {{appdate}}</option>
        {% else %}
            <option value="{{appdate|date:'Y-m-d'}}">{{appdate|date:"l"}} {{appdate}}</option>
        {% endif %}
    {% endfor %}
</select>

main/customers/templates/customers/availTimes_ajax.html
<select class="form-control" name="time" id="time">
    {% for time in availTimes %}
        {% if time == prefer_time %}
            <option selected value="{{time|date:'Y-m-d H:i:s'}}">{{time|date:'H:i'}}</option>
        {% else %}
            <option value="{{time|date:'Y-m-d H:i:s'}}">{{time|date:'H:i'}}</option>
        {% endif %}
    {% endfor %}
</select>

main/customers/templates/customers/box_cleaned.html
{% extends 'customers/base.html' %}
{% block content %}

<h1> Kits Checked</h1>
<a class="btn btn-primary ml-auto" style="margin-left: 20px;" href="{% url 'appointments' %}">Appointments</a>
{% endblock %}

main/customers/templates/customers/customer_update.html
{% extends "customers/base.html" %}
{% load crispy_forms_tags %}
{% block content %}





<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-6">
            <h3>Update customer info</h3>
            <h4>Customer: {{customer}}</h4>
            {% if not locker %}
            <a class="btn btn-primary ml-auto" style="margin-left: 20px;" href="{% url 'delete-customer' customer.pk %}">Duplicate customer delete</a>
            {% endif %}
            <div class="form-group">
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        {% if cus_appointments %}
                        <h5>Appointments</h5>
                        {% for item in cus_appointments %}
                        <div><a  href="{% url 'update-appointment' item.pk %}">{{item.dateTime}} {{item.service}}</a></div>
                        {% endfor %}
                        {% endif %}
                        {% if not_turned_up %}
                        <h5>Not turned up</h5>
                        {% for item in not_turned_up %}
                        <div>{{item.dateTime}} {{item.service}}
                        {% endfor %}
                        {% endif %}
                        </div>
                        <table cellspacing="0" cellpadding="0" border="0" width="500">
                          <div>
                              <tr>
                                  <th width="150">FirstName</th>
                                  <th width="150">LastName</th>
                                  <th width="150">Mobile</th>
  
                              </tr>
                          </div>
                      </table>
                          <div>
                              <table id="myTable" style="width:500px; height:100px; overflow:auto;">
  
                              {% for cust in customers %}
                               <tr>
                                  <td width="150">{{cust.firstName}}</td>
                                  <td width="150">{{cust.lastName}}</td>
                                  <td width="150">{{cust.mobile}}</td>
                               </tr>
                               {% endfor %}
                             </table>  
                           </div>
                        <br>
                        <h3>Customer</h3>
                                <div><label width="150" for="id_firstName">FirstName:</label> <input type="text" name="firstName" maxlength="50" id="id_firstName" value={{customer.firstName}} autofocus></div>             
                                <div><label width="150" for="id_lastName">LastName:</label> <input type="text" name="lastName" maxlength="50" id="id_lastName" value={{customer.lastName}}></div>
                                <div><label width="150" for="id_mobile">Mobile:</label> <input type="text" name="mobile" maxlength="11" id="id_mobile" value={{customer.mobile}}></div>
                                <div><label width="150" for="id_notice">Notice:</label></div>
                                

                                <textarea id="id_notice" name="notice" rows="4" cols="50">{{customer.notice}}</textarea>
 
                                {% if not locker %}
                                <p><label for="id_postCode">Box:</label>
                                    <select name="locker" id="id_locker">
                                        {% for locker in lockers %}
                                        <option value={{locker}}>{{locker}}</option>
                                        {% endfor %}
                                      
            
                                    </select>
                                </p>
                                {% endif %}
                                <div>
                                  <button class="btn btn-sucess btn-outline-info" type="submit">Save</button>

                                </div>

                    

                    </form>
                     


              <style>
                  /* scrolltable rules */
                table  { margin-top:  20px; display: inline-block; overflow: auto; }
                th div { margin-top: -20px; position: absolute; }

                /* design */
                table { border-collapse: collapse; }
                tr:nth-child(even) { background: #EEE; }
              </style>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("#id_firstName").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
  $("tr").click(function(){
    var values = $(this).text();
    values = values.replace(/(\r\n|\n|\r)/gm," ");
    values = values.replace(/\s+/g," ");
    values = values.split(' ')
    document.getElementById('id_firstName').value = values[1];
    document.getElementById('id_lastName').value = values[2];
    document.getElementById('id_mobile').value = values[3];
  });
});





</script>


{% endblock content %}